delineo: 
  name: Delineo Disease Modeling Project
  origin: Johns Hopkins University
  enabled: true 
  imageURL: docker.pkg.github.com/covid-policy-modelling/model-connector-template/model-connector:latest # URL of your published Docker container
  metaURLs: 
    code: https://github.com/Ehong-Sun/Covid-UI-Connector.git
    website: https://covidweb.isi.jhu.edu/
  description: |
    A template for adding new models
    A short description of your model, around a paragraph, to be displayed in the UI
  supportedParameters: # Delete parameters (as supplied in the input schema) that your model connector does not support
    - interventionStrategies
    - contactReduction
    - r0
  supportedRegions: # List regions and subregions (as described in the input schema) that your model connector supports
    US:
      - US # If the connector supports both the top-level region and some subregions, you must explicitly repeat the top-level region in the array
      - US-AK
    IE: # As a convenience, you can use a missing value if the connector only supports the top-level region
    CA: [] # Or an empty array
